PUT http://localhost:3000/barbers/6228b12e31e2043fddf45821/bookings/622b192d0f7efd220432e4a9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjI4YjA4YWM4YmZmYjMyODNmNWNmMjkiLCJpYXQiOjE2NDY5ODk4MTMsImV4cCI6MTY0NzA3NjIxM30.UCJ-1ZdFkBqOk-LStE0O52vFklh7M-NdwsY-U2Rfgyk

{
    "sessionNumber": "3",
    "style": "High fade"

}

###

POST http://localhost:3000/contact
Content-Type: application/json

{
    "name":"muneeb",
    "email":"muneeb@gmail.com",
    "message":"testing??"
}


###
PATCH  http://localhost:3000/customers/622c54f0b240cb1a022adc1b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjJjNTRmMGIyNDBjYjFhMDIyYWRjMWIiLCJpYXQiOjE2NDc1MDUyODAsImV4cCI6MTY0NzU5MTY4MH0.IJBzRIcvxH9qXVAyPQ5UJh5tbOXgyCsd0jwmmZ-hL2g

{
        "customername": "SuhailTEE",
        "password": "suhail",
         "email": "suhail@gmail.com",
         "phone_number":"0761621649"
}

#  "email": "suhail@suhail.com",
#         "phone_number":"1234567890"
# 622c54f0b240cb1a022adc1b