PUT http://localhost:3000/barbers/6228b12e31e2043fddf45821/bookings/622b192d0f7efd220432e4a9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjI4YjA4YWM4YmZmYjMyODNmNWNmMjkiLCJpYXQiOjE2NDY5ODk4MTMsImV4cCI6MTY0NzA3NjIxM30.UCJ-1ZdFkBqOk-LStE0O52vFklh7M-NdwsY-U2Rfgyk

{
    "sessionNumber": "3",
    "style": "High fade"

}

###

POST http://localhost:3000/barbers/naaim/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMyYjcxZjU5MmIzODQ5NWMyYmRhMzkiLCJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE2NDc1OTIwMDcsImV4cCI6MTY0NzY3ODQwN30.rlBPEOHb-OJBdTauils5A1l-8tCWhtrONhmu8iToZgg

{
    "sessionNumber": "session 1",
    "style":"head shave"
    
}


###
POST  http://localhost:3000/customers/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjJjNTRmMGIyNDBjYjFhMDIyYWRjMWIiLCJpYXQiOjE2NDc1MDUyODAsImV4cCI6MTY0NzU5MTY4MH0.IJBzRIcvxH9qXVAyPQ5UJh5tbOXgyCsd0jwmmZ-hL2g

{
        "customername": "Zubaidah",
        "password": "baidah"
     
}

###

GET http://localhost:3000/customers/6229b2504c228355412a8ca9#


###
POST http://localhost:3000/customers/
